// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniTms.Data;

#nullable disable

namespace MiniTms.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523084933_AddTmsSchema")]
    partial class AddTmsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MiniTms.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MiniTms.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVip")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Tây Hồ",
                            IsDeleted = false,
                            IsVip = true,
                            Latitude = 21.07,
                            Longitude = 105.81999999999999,
                            Name = "Cafe Highland Tây Hồ"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Đống Đa",
                            IsDeleted = false,
                            IsVip = false,
                            Latitude = 21.015000000000001,
                            Longitude = 105.83,
                            Name = "Tiệm cơm Đống Đa"
                        },
                        new
                        {
                            CustomerId = 3,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Long Biên",
                            IsDeleted = false,
                            IsVip = false,
                            Latitude = 21.039999999999999,
                            Longitude = 105.90000000000001,
                            Name = "Văn phòng Long Biên"
                        },
                        new
                        {
                            CustomerId = 4,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Hà Đông",
                            IsDeleted = false,
                            IsVip = false,
                            Latitude = 20.969999999999999,
                            Longitude = 105.76000000000001,
                            Name = "Trường THCS Hà Đông"
                        },
                        new
                        {
                            CustomerId = 5,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Hoàn Kiếm",
                            IsDeleted = false,
                            IsVip = true,
                            Latitude = 21.029,
                            Longitude = 105.852,
                            Name = "Khách sạn Hoàn Kiếm"
                        },
                        new
                        {
                            CustomerId = 6,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Ba Đình",
                            IsDeleted = false,
                            IsVip = false,
                            Latitude = 21.035,
                            Longitude = 105.81,
                            Name = "Quán phở Ba Đình"
                        },
                        new
                        {
                            CustomerId = 7,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Thanh Xuân",
                            IsDeleted = false,
                            IsVip = false,
                            Latitude = 20.995000000000001,
                            Longitude = 105.795,
                            Name = "Trung tâm Thanh Xuân"
                        },
                        new
                        {
                            CustomerId = 8,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            District = "Hai Bà Trưng",
                            IsDeleted = false,
                            IsVip = false,
                            Latitude = 21.004999999999999,
                            Longitude = 105.86499999999999,
                            Name = "Siêu thị Hai Bà Trưng"
                        });
                });

            modelBuilder.Entity("MiniTms.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<TimeOnly>("DeliveryEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("DeliveryStart")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NEW");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderDate", "Status");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = 1001,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 1,
                            DeliveryEnd = new TimeOnly(9, 0, 0),
                            DeliveryStart = new TimeOnly(7, 0, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 120.0
                        },
                        new
                        {
                            OrderId = 1002,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 2,
                            DeliveryEnd = new TimeOnly(10, 0, 0),
                            DeliveryStart = new TimeOnly(7, 30, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 80.0
                        },
                        new
                        {
                            OrderId = 1003,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 3,
                            DeliveryEnd = new TimeOnly(11, 0, 0),
                            DeliveryStart = new TimeOnly(8, 0, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 450.0
                        },
                        new
                        {
                            OrderId = 1004,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 4,
                            DeliveryEnd = new TimeOnly(10, 0, 0),
                            DeliveryStart = new TimeOnly(7, 0, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 300.0
                        },
                        new
                        {
                            OrderId = 1005,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 5,
                            DeliveryEnd = new TimeOnly(8, 30, 0),
                            DeliveryStart = new TimeOnly(7, 0, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 60.0
                        },
                        new
                        {
                            OrderId = 1006,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 6,
                            DeliveryEnd = new TimeOnly(10, 30, 0),
                            DeliveryStart = new TimeOnly(7, 30, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 200.0
                        },
                        new
                        {
                            OrderId = 1007,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 7,
                            DeliveryEnd = new TimeOnly(11, 0, 0),
                            DeliveryStart = new TimeOnly(8, 0, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 900.0
                        },
                        new
                        {
                            OrderId = 1008,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            CustomerId = 8,
                            DeliveryEnd = new TimeOnly(9, 30, 0),
                            DeliveryStart = new TimeOnly(7, 0, 0),
                            IsDeleted = false,
                            OrderDate = new DateOnly(2026, 5, 23),
                            Status = "NEW",
                            WeightKg = 150.0
                        });
                });

            modelBuilder.Entity("MiniTms.Entities.RateCard", b =>
                {
                    b.Property<int>("RateCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateCardId"));

                    b.Property<decimal>("BaseCost")
                        .HasColumnType("decimal(12,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("DropFee")
                        .HasColumnType("decimal(12,0)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ToDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RateCardId");

                    b.HasIndex("VendorCode", "ToDistrict", "VehicleType")
                        .IsUnique();

                    b.ToTable("RateCard", (string)null);

                    b.HasData(
                        new
                        {
                            RateCardId = 1,
                            BaseCost = 250000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 30000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Tây Hồ",
                            VehicleType = "1.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 2,
                            BaseCost = 320000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 30000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Tây Hồ",
                            VehicleType = "2.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 3,
                            BaseCost = 480000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 30000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Tây Hồ",
                            VehicleType = "5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 4,
                            BaseCost = 200000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 25000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Đống Đa",
                            VehicleType = "1.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 5,
                            BaseCost = 270000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 25000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Đống Đa",
                            VehicleType = "2.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 6,
                            BaseCost = 350000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 35000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Long Biên",
                            VehicleType = "2.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 7,
                            BaseCost = 520000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 35000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Long Biên",
                            VehicleType = "5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 8,
                            BaseCost = 380000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 40000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Hà Đông",
                            VehicleType = "2.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 9,
                            BaseCost = 550000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 40000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Hà Đông",
                            VehicleType = "5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 10,
                            BaseCost = 220000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 25000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Hoàn Kiếm",
                            VehicleType = "1.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 11,
                            BaseCost = 230000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 25000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Ba Đình",
                            VehicleType = "1.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 12,
                            BaseCost = 290000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 30000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Thanh Xuân",
                            VehicleType = "2.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 13,
                            BaseCost = 450000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 30000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Thanh Xuân",
                            VehicleType = "5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 14,
                            BaseCost = 240000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 25000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Hai Bà Trưng",
                            VehicleType = "1.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            RateCardId = 15,
                            BaseCost = 460000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 30000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Tây Hồ",
                            VehicleType = "5T",
                            VendorCode = "V2"
                        },
                        new
                        {
                            RateCardId = 16,
                            BaseCost = 500000m,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            DropFee = 35000m,
                            IsActive = true,
                            IsDeleted = false,
                            ToDistrict = "Long Biên",
                            VehicleType = "5T",
                            VendorCode = "V2"
                        });
                });

            modelBuilder.Entity("MiniTms.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(12,0)");

                    b.Property<double>("TotalKm")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.HasIndex("PlanCode");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("MiniTms.Entities.TripOrder", b =>
                {
                    b.Property<int>("TripOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripOrderId"));

                    b.Property<TimeOnly>("EtaTime")
                        .HasColumnType("time");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StopIndex")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("TripOrderId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("TripId", "OrderId")
                        .IsUnique();

                    b.ToTable("TripOrders", (string)null);
                });

            modelBuilder.Entity("MiniTms.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<double>("CapacityKg")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CapacityKg = 1500.0,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            IsActive = true,
                            IsDeleted = false,
                            Plate = "29C-111.11",
                            VehicleType = "1.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            VehicleId = 2,
                            CapacityKg = 2500.0,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            IsActive = true,
                            IsDeleted = false,
                            Plate = "29C-222.22",
                            VehicleType = "2.5T",
                            VendorCode = "V1"
                        },
                        new
                        {
                            VehicleId = 3,
                            CapacityKg = 5000.0,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            IsActive = true,
                            IsDeleted = false,
                            Plate = "29C-333.33",
                            VehicleType = "5T",
                            VendorCode = "V2"
                        },
                        new
                        {
                            VehicleId = 4,
                            CapacityKg = 2500.0,
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "seed",
                            IsActive = false,
                            IsDeleted = false,
                            Plate = "29C-444.44",
                            VehicleType = "2.5T",
                            VendorCode = "V2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MiniTms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MiniTms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("MiniTms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniTms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MiniTms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniTms.Entities.Order", b =>
                {
                    b.HasOne("MiniTms.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiniTms.Entities.Trip", b =>
                {
                    b.HasOne("MiniTms.Entities.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("MiniTms.Entities.TripOrder", b =>
                {
                    b.HasOne("MiniTms.Entities.Order", "Order")
                        .WithOne("TripOrder")
                        .HasForeignKey("MiniTms.Entities.TripOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiniTms.Entities.Trip", "Trip")
                        .WithMany("TripOrders")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("MiniTms.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MiniTms.Entities.Order", b =>
                {
                    b.Navigation("TripOrder");
                });

            modelBuilder.Entity("MiniTms.Entities.Trip", b =>
                {
                    b.Navigation("TripOrders");
                });

            modelBuilder.Entity("MiniTms.Entities.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
